const ACTION_TYPE = {
  FETCH_ALL_WIDGETS_REQUESTED: 'FETCH_ALL_WIDGETS_REQUESTED',
  FETCH_ALL_WIDGETS_SUCCESS: 'FETCH_ALL_WIDGETS_SUCCESS',
  FETCH_ALL_WIDGETS_FAILURE: 'FETCH_ALL_WIDGETS_FAILURE',
};

export default ACTION_TYPE;
